//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivArts.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Affectation
    {
        public int BenevoleId { get; set; }
        public int CreneauId { get; set; }
        public int PlanningId { get; set; }
    
        public virtual Benevole Benevole { get; set; }
        public virtual Creneau Creneau { get; set; }
        public virtual Planning Planning { get; set; }
    }
}
