//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivArts.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentaireDispo
    {
        public int BenevoleId { get; set; }
        public int JourId { get; set; }
        public string Commentaire { get; set; }
    
        public virtual Benevole Benevole { get; set; }
        public virtual JourEvenement JourEvenement { get; set; }
    }
}
