//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivArts.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FestivArtsContext : DbContext
    {
        public FestivArtsContext()
            : base("name=FestivArtsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affectation> Affectations { get; set; }
        public virtual DbSet<Benevole> Benevoles { get; set; }
        public virtual DbSet<CommentaireDispo> CommentaireDispoes { get; set; }
        public virtual DbSet<Conf> Confs { get; set; }
        public virtual DbSet<Creneau> Creneaux { get; set; }
        public virtual DbSet<CreneauDef> CreneauDefs { get; set; }
        public virtual DbSet<Dispo> Dispoes { get; set; }
        public virtual DbSet<JourEvenement> JourEvenements { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Tache> Taches { get; set; }
        public virtual DbSet<TypeTache> TypeTaches { get; set; }
    }
}
